import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";


//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900","600"], // range of weights
  style: ["normal"], 
  display: "swap",
});

// 
export const metadata: Metadata = {
  title: "ziPay-Yc Dedicated",
  description: "Generated by create next app",
};


// 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className} >
         
        {children}
      </body>
    </html>
  );
}
