import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";


//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900","600"], // range of weights
  style: ["normal"], 
  display: "swap",
});

// 
// export const metadata: Metadata = {
//   title: "ziPay-Yc Dedicated",
//   description: "Generated by create next app",
// };


export const metadata = {
  title: "ziPay – Fast and Simple Global Payments",
  description:
    "ziPay is a fast and simple way to send and receive money across borders. With one wallet, instant conversions, and fair rates, we make global payments seamless, affordable, and stress-free for individuals and businesses alike.",
  keywords: [
    "ziPay",
    "money transfer",
    "cross-border payments",
    "digital wallet",
    "global remittance",
    "currency conversion",
    "fintech",
    "nextjs",
    "react",
  ],
  openGraph: {
    title: "ziPay – Fast and Simple Global Payments",
    description:
      "Send and receive money across borders instantly with ziPay. One wallet, instant conversions, and fair rates for individuals and businesses.",
    url: "https://zipay-yc.vercel.app", 
    siteName: "ziPay",
    images: [
      {
        url: "/app.png", 
        width: 1200,
        height: 630,
        alt: "ziPay app preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ziPay – Fast and Simple Global Payments",
    description:
      "Send and receive money worldwide with ziPay. Simple, fast, and affordable.",
    images: ["/Macbook.png"],
    creator: "@ziPay", 
  },
  icons: {
    icon: "/Temp Logo.png",
    shortcut: "/Temp Logo.png",
  },
};


// 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className} >
         
        {children}
      </body>
    </html>
  );
}
